Improved Chapter 1 and 2 a bit
denkspuren/JavaLernfragen pull request #19
Opened 2017-10-19 11:48 UTC by blackus3r

I have added some hints and examples to the answers of chapter 1 and 2. 

Generated html code with Asciidoctor 1.5.6.1

Ich hätte gern mehr geschafft, allerdings bin ich durch meine Hand, wie sie gesehen haben, ein wenig verhindert.

2017-10-20 13:34 UTC, denkspuren commented on Fragen/Kap.1.8.adoc
> +Anweisung => "a = 2+2" +
Unglücklich ist, dass das Beispiel mit der Anweisung ausgerechnet nicht mit einem Semikolon endet. Obwohl die Frage darauf abzielte.

2017-10-20 13:36 UTC, denkspuren commented on Fragen/Kap.1.8.adoc
> +Neben der Klasse `Math` befindet sich beispielsweise auch die Klasse `String` in `java.lang.
Es fehlt am Ende von `java.lang` das abschließende Hochkomma.

2017-10-20 13:41 UTC, denkspuren commented on Fragen/Kap.2.adoc
> +*Beispiel:* `1 + 3.5`
Es müsste `1 + 3.5f` heißen, denn ohne `f` ist es ein `double`, was nicht zum Text passt. Vielleicht passen wir besser den Text an und reden dort vom `double` statt vom `float`.

2017-10-20 13:42 UTC, denkspuren commented on Fragen/Kap.2.adoc
> +`1E6` gleicht 1*10^6.
Wird das korrekt gerendert? Muss es in Asciidoc nicht `1 * 10^6^` heißen?

2017-10-20 13:43 UTC, denkspuren commented on Fragen/Kap.2.adoc
> +*Beispiel:* Wenn man die Koordinaten für p1 ändert, werden auch die Koordinaten von p2 und p3 geändert, somit sind sie zu jedem Zeitpunkt gleich. +
p1, p2, p2 bitte als `p1`, `p2`, `p3` schreiben (mit Hochkommata). Danke!

2017-10-20 13:46 UTC, denkspuren requested changes
Danke für Ihre Ergänzungen, finde ich toll. Schauen Sie sich die Kommentare an? Dann kann ich die Änderungen übernehmen.

2017-10-22 16:42 UTC, blackus3r commented
Ich habe die Sachen korrigiert. 
Außerdem habe ich den Commit zum Generieren der HTML-Dateien wieder rückgängig gemacht. Am besten sollte dies im Master geschehen. 

Grüße

2017-10-22 21:31 UTC, denkspuren approved these changes
Prima!

2017-10-22 21:32 UTC, merged