Verbesserungen für Kapitel 2 und 3
denkspuren/JavaLernfragen pull request #21
Opened 2017-10-27 16:00 UTC by blackus3r

2017-11-08 00:04 UTC, denkspuren requested changes
Das sind alles gute Vorschläge und Ergänzungen. Nur führen Sie stets das `+`-Zeichen in den Texten ein, was das Erscheinungsbild unglücklich verändert. Könnten Sie das anpassen? (Sie sehen, wir haben das nirgends sonst so gemacht.) Dann übernehme ich gerne Ihre Änderungen.

2017-11-08 15:09 UTC, blackus3r commented
Die `+`-Zeichen erzwingen doch einen Zeilenumbruch, richtig?

2017-11-10 22:10 UTC, denkspuren commented
Ja schon (http://asciidoctor.org/docs/asciidoc-writers-guide/#wrapped-text-and-hard-line-breaks), aber wozu? Wie gesagt: Schauen Sie sich die Dokumente an, man kommt vollkommen ohne aus.

2017-11-21 08:19 UTC, denkspuren approved these changes
Super, danke!

2017-11-21 08:19 UTC, merged